elasticsearch/esclean.py: add missing schema argument
Fixes:
```
TypeError: __init__() missing 1 required positional argument: 'scheme'
```

Signed-off-by: Jakub Sokołowski <jakub@status.im>